name: timesheet
description: A flutter application to enter timesheet

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path_provider: ^2.0.1
  intl: ^0.17.0
  charts_flutter: ^0.10.0
  month_picker_dialog: ^0.4.0
  pdf: ^3.2.0
  open_file: ^3.2.0
  #printing: ^4.1.0
  #flutter_html_view: ^0.3.1
  # Authentication using flutter_appauth https://auth0.auth0.com/u/login
  #http: ^0.12.1
  #flutter_appauth: ^0.9.1
  flutter_secure_storage: ^4.1.0
  # Authentication using Firebase, all firebase products now depend on firebase_core version 0.5.0+
  firebase_core : ^1.0.4
  firebase_auth: ^1.1.1
  #firebase_dynamic_links: ^0.5.1
  google_sign_in: ^5.0.2
  ffi: ^1.0.0 #this dependancy is added to resolve issues created after switching to flutter master branch



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "icons/ic_launcher.png"
  android: true
  ios: true
# flutter pub run flutter_launcher_icons:main --> run this command to change android launcher icon
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/profile.png
  - images/icon.png
  - images/google.png
  - images/background.jpeg
  - images/CreateProject.png
  - images/CreateTimeSheet.png
  - images/StartTimer.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OpenSans
       fonts:
         - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
